[package]
name = "key-convertr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bech32 = "0.9.1"
clap = { version = "4.0.32", features = ["derive"] }
hex = "0.4.3"